spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person-db
    username: admin
    password: gjkybrjd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
com:
  mcfly:
    prop1: 1
    prop2: a